name: Periodic Health Check

# on:
#   schedule:
#     - cron: '30 5,17 * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Periodic Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://tj-pokedex.herokuapp.com/
