name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
  current_date_job:
    runs-on: ubuntu-latest
    steps:
     - name: Current date
       run: date
  directory_content_job:
    runs-on: ubuntu-latest
    steps:
     - name: Directory content
       run: ls -l